#Curso Básico de Python
#Nome do desenvolvedor: ANA LUIZA DE MORAIS BELLINI
#Versão 1.0
#Exercício de lógica de programação
#Com a linguagem de programação Python
#Exercício: 4) Faça um programa que receba três notas de um 
# aluno e calcule sua média.

nota1=float(input("Digite a primeira nota: "))
nota2=float(input("Digite a segunda nota: "))
nota3=float(input("Digite a terceira nota: "))
media=(nota1+nota2+nota3)/3
print("A média das notas é:", media)
print("OBRIGADA POR UTILIZAR O PROGRAMA >3")